# Generated by Django 4.2.7 on 2023-11-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image',
        ),
    ]
