# Generated by Django 4.2.7 on 2023-11-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_remove_hotel_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_image/'),
        ),
    ]
