# Generated by Django 4.2.7 on 2023-11-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed')], max_length=50, null=True),
        ),
    ]
